         
#########################################################
[[start task]]
2019-06-15 10:28:27
HTTPSConnectionPool(host='api.coinone.co.kr', port=443): Max retries exceeded with url: /ticker/?currency=btc (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbd53f3ca10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
btc : Response Success!
Traceback (most recent call last):
  File "./Collect/main.py", line 39, in <module>
    main()
  File "./Collect/main.py", line 27, in main
    parser.save(response, currency)
  File "/home/zeus/workspace/dees2projectteam2/Collect/fastcampus/dees2/projectteam2/coinone.py", line 37, in save
    result = response.json()
AttributeError: 'str' object has no attribute 'json'
         
[[git run]]
2019-06-15 10:28:29
[master e004fbf3] auto git push
 2 files changed, 30 insertions(+)
 create mode 100644 log/collect_2019061510.log
ssh: Could not resolve hostname github.com: Temporary failure in name resolution
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
         
[[end task]]
2019-06-15 10:28:30
         
#########################################################
[[start task]]
2019-06-15 10:35:43
btc : Response Success!
Traceback (most recent call last):
  File "./Collect/main.py", line 39, in <module>
    main()
  File "./Collect/main.py", line 27, in main
    parser.save(response, currency)
  File "/home/zeus/workspace/dees2projectteam2/Collect/fastcampus/dees2/projectteam2/coinone.py", line 38, in save
    date = result["timestamp"]
KeyError: 'timestamp'
         
[[git run]]
2019-06-15 10:35:49
